require_relative '../../node_modules/capacitor-plugin-bbd-base/scripts/hooks/ios/update_deployment_target.rb'
require_relative '../../node_modules/capacitor-plugin-bbd-base/scripts/hooks/ios/update_deployment_target.rb'
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
	pod 'BlackBerryDynamics', :podspec => 'https://software.download.blackberry.com/repository/framework/dynamics/ios/11.0.1.137/BlackBerryDynamics-11.0.1.137.podspec'
	pod 'BlackBerryDynamics', :podspec => 'https://software.download.blackberry.com/repository/framework/dynamics/ios/11.0.1.137/BlackBerryDynamics-11.0.1.137.podspec'
end


post_install do |installer|
   project = Xcodeproj::Project.open('App.xcodeproj')
   update_deployment_target project, 14.0
   project.save

   update_deployment_target installer.pods_project, 14.0
endpost_install do |installer|
   project = Xcodeproj::Project.open('App.xcodeproj')
   update_deployment_target project, 14.0
   project.save

   update_deployment_target installer.pods_project, 14.0
end